steps:
  - name: "gcr.io/coud-builders/dockers"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/user", "."]
  - name: "gcr.io/coud-builders/dockers"
    args: ["push","gcr.io/$PROJECT_ID/user"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "user",
      "--image",
      "gcr.io/$PROJECT_ID/user",
      "--port",
      "3100",
      "--region",
      "asia-shouteast2",
      "--platform",
      "managed",
      "allow-unauthenticated",
    ]
